stations = {'shoutcast': [{'hosts': ['http://scfire-chi0l-1.stream.aol.com/stream/1018',
                          'http://scfire-dll-aa03.stream.aol.com:80/stream/1018',
                          'http://scfire-chi0l-2.stream.aol.com:80/stream/1018',
                          'http://scfire-dll-aa02.stream.aol.com:80/stream/1018',
                          'http://scfire-dll-aa01.stream.aol.com:80/stream/1018',
                          'http://scfire-nyk-aa01.stream.aol.com:80/stream/1018',
                          'http://steady.somafm.com:8032',
                          'http://fx.somafm.com:8032'],
                'title': 'Groove Salad'},
               {'hosts': ['http://scfire-dll-aa03.stream.aol.com:80/stream/1021',
                          'http://scfire-chi0l-1.stream.aol.com/stream/1021',
                          'http://scfire-ntc-aa03.stream.aol.com:80/stream/1021',
                          'http://scfire-dll-aa02.stream.aol.com:80/stream/1021',
                          'http://scfire-dll-aa01.stream.aol.com:80/stream/1021',
                          'http://scfire-nyk-aa01.stream.aol.com:80/stream/1021',
                          'http://fx.somafm.com:8002'],
                'title': 'Secret Agent'},
               {'hosts': ['http://scfire-chi0l-1.stream.aol.com/stream/1032',
                          'http://scfire-chi0l-2.stream.aol.com:80/stream/1032',
                          'http://scfire-dll-aa03.stream.aol.com:80/stream/1032',
                          'http://scfire-dll-aa02.stream.aol.com:80/stream/1032',
                          'http://scfire-dll-aa01.stream.aol.com:80/stream/1032',
                          'http://scfire-nyk-aa01.stream.aol.com:80/stream/1032',
                          'http://fx.somafm.com:8004'],
                'title': 'Drone Zone'},
               {'hosts': ['http://steady.somafm.com:8000',
                          'http://fx.somafm.com:8080',
                          'http://207.200.96.231:8012'],
                'title': 'Space Station'},
               {'hosts': ['http://steady.somafm.com:8800',
                          'http://fx.somafm.com:8800'],
                'title': 'Lush'},
               {'hosts': ['http://steady.somafm.com:8900',
                          'http://fx.somafm.com:8900'],
                'title': 'Digitalis'},
               {'hosts': ['http://steady.somafm.com:8388',
                          'http://207.200.96.232:8006'],
                'title': 'Beat Blender'},
               {'hosts': ['http://scfire-dll-aa02.stream.aol.com:80/stream/1073',
                          'http://scfire-chi0l-2.stream.aol.com:80/stream/1073',
                          'http://scfire-chi0l-2.stream.aol.com:80/stream/1073',
                          'http://scfire-nyk-aa01.stream.aol.com:80/stream/1073',
                          'http://scfire-dll-aa01.stream.aol.com:80/stream/1073',
                          'http://scfire-dll-aa03.stream.aol.com:80/stream/1073'],
                'title': 'Indie Pop Rocks'},
               {'hosts': ['http://207.200.96.231:8014'], 'title': 'Cliqhop'},
               {'hosts': ['http://steady.somafm.com:8600',
                          'http://fx.somafm.com:8600'],
                'title': 'Sonic Universe'},
               {'hosts': ['http://steady.somafm.com:8500'],
                'title': 'Illinois Street Lounge'},
               {'hosts': ['http://207.200.96.230:8014',
                          'http://steady.somafm.com:7000'],
                'title': 'Boot Liquor'},
               {'hosts': ['http://205.188.215.230:8012'],
                'title': 'Tags Trip Trance'},
               {'hosts': ['http://steady.somafm.com:8300'],
                'title': 'Doomed'}]}