# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/lastcast_main.ui'
#
# Created: Wed Oct 01 21:15:55 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_LastcastMainWindow(object):
    def setupUi(self, LastcastMainWindow):
        LastcastMainWindow.setObjectName("LastcastMainWindow")
        LastcastMainWindow.resize(356, 250)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ui/img/transmit_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LastcastMainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(LastcastMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(-5, 0, 535, 71))
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(5, 10, 206, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(31)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setPixmap(QtGui.QPixmap(":/ui/img/lastcast.png"))
        self.label_4.setObjectName("label_4")
        self.slideVolume = QtGui.QSlider(self.centralwidget)
        self.slideVolume.setGeometry(QtCore.QRect(35, 195, 315, 25))
        self.slideVolume.setOrientation(QtCore.Qt.Horizontal)
        self.slideVolume.setObjectName("slideVolume")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(-5, 70, 380, 56))
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.btnPlay = QtGui.QToolButton(self.groupBox_2)
        self.btnPlay.setEnabled(False)
        self.btnPlay.setGeometry(QtCore.QRect(5, 5, 50, 45))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ui/img/control_play_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlay.setIcon(icon1)
        self.btnPlay.setIconSize(QtCore.QSize(25, 25))
        self.btnPlay.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnPlay.setAutoRaise(True)
        self.btnPlay.setObjectName("btnPlay")
        self.btnStop = QtGui.QToolButton(self.groupBox_2)
        self.btnStop.setEnabled(False)
        self.btnStop.setGeometry(QtCore.QRect(55, 5, 50, 45))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ui/img/control_stop_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStop.setIcon(icon2)
        self.btnStop.setIconSize(QtCore.QSize(25, 25))
        self.btnStop.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnStop.setAutoRaise(True)
        self.btnStop.setObjectName("btnStop")
        self.btnStations = QtGui.QToolButton(self.groupBox_2)
        self.btnStations.setGeometry(QtCore.QRect(255, 5, 50, 45))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ui/img/transmit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStations.setIcon(icon3)
        self.btnStations.setIconSize(QtCore.QSize(25, 25))
        self.btnStations.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnStations.setAutoRaise(True)
        self.btnStations.setObjectName("btnStations")
        self.btnBan = QtGui.QToolButton(self.groupBox_2)
        self.btnBan.setEnabled(False)
        self.btnBan.setGeometry(QtCore.QRect(205, 5, 50, 45))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ui/img/bomb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBan.setIcon(icon4)
        self.btnBan.setIconSize(QtCore.QSize(25, 25))
        self.btnBan.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnBan.setAutoRaise(True)
        self.btnBan.setObjectName("btnBan")
        self.btnRecord = QtGui.QToolButton(self.groupBox_2)
        self.btnRecord.setEnabled(False)
        self.btnRecord.setGeometry(QtCore.QRect(105, 5, 50, 45))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ui/img/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRecord.setIcon(icon5)
        self.btnRecord.setIconSize(QtCore.QSize(25, 25))
        self.btnRecord.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnRecord.setAutoRaise(True)
        self.btnRecord.setObjectName("btnRecord")
        self.btnLove = QtGui.QToolButton(self.groupBox_2)
        self.btnLove.setEnabled(False)
        self.btnLove.setGeometry(QtCore.QRect(155, 5, 50, 45))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/ui/img/heart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLove.setIcon(icon6)
        self.btnLove.setIconSize(QtCore.QSize(25, 25))
        self.btnLove.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnLove.setAutoRaise(True)
        self.btnLove.setObjectName("btnLove")
        self.btnSettings = QtGui.QToolButton(self.groupBox_2)
        self.btnSettings.setEnabled(True)
        self.btnSettings.setGeometry(QtCore.QRect(305, 5, 50, 45))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/ui/img/wrench.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSettings.setIcon(icon7)
        self.btnSettings.setIconSize(QtCore.QSize(25, 25))
        self.btnSettings.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnSettings.setAutoRaise(True)
        self.btnSettings.setObjectName("btnSettings")
        self.title = QtGui.QLineEdit(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(35, 135, 314, 25))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.title.setFont(font)
        self.title.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.title.setReadOnly(True)
        self.title.setObjectName("title")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(11, 140, 18, 17))
        self.label.setPixmap(QtGui.QPixmap(":/ui/img/music.png"))
        self.label.setObjectName("label")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 200, 20, 17))
        self.label_3.setPixmap(QtGui.QPixmap(":/ui/img/sound.png"))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 170, 15, 17))
        self.label_2.setPixmap(QtGui.QPixmap(":/ui/img/transmit.png"))
        self.label_2.setObjectName("label_2")
        self.editStation = QtGui.QLineEdit(self.centralwidget)
        self.editStation.setGeometry(QtCore.QRect(35, 165, 314, 25))
        self.editStation.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.editStation.setReadOnly(True)
        self.editStation.setObjectName("editStation")
        LastcastMainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(LastcastMainWindow)
        self.statusBar.setAutoFillBackground(False)
        self.statusBar.setStyleSheet("""background-color: rgb(158, 158, 158);
color: rgb(230, 230, 230);""")
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName("statusBar")
        LastcastMainWindow.setStatusBar(self.statusBar)
        self.actionPlay = QtGui.QAction(LastcastMainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/ui/resources/ui/control_play_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay.setIcon(icon8)
        self.actionPlay.setObjectName("actionPlay")
        self.actionStop = QtGui.QAction(LastcastMainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/ui/resources/ui/control_stop_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon9)
        self.actionStop.setObjectName("actionStop")
        self.actionRecord = QtGui.QAction(LastcastMainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/ui/resources/ui/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecord.setIcon(icon10)
        self.actionRecord.setObjectName("actionRecord")
        self.actionLove = QtGui.QAction(LastcastMainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/ui/resources/ui/heart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLove.setIcon(icon11)
        self.actionLove.setObjectName("actionLove")
        self.actionBan = QtGui.QAction(LastcastMainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/ui/resources/ui/bomb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBan.setIcon(icon12)
        self.actionBan.setObjectName("actionBan")
        self.actionStations = QtGui.QAction(LastcastMainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/ui/resources/ui/transmit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStations.setIcon(icon13)
        self.actionStations.setObjectName("actionStations")
        self.actionSettings = QtGui.QAction(LastcastMainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/ui/resources/ui/wrench.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon14)
        self.actionSettings.setObjectName("actionSettings")

        self.retranslateUi(LastcastMainWindow)
        QtCore.QObject.connect(self.btnPlay, QtCore.SIGNAL("clicked()"), LastcastMainWindow.play)
        QtCore.QObject.connect(self.btnStop, QtCore.SIGNAL("clicked()"), LastcastMainWindow.stop)
        QtCore.QObject.connect(self.btnRecord, QtCore.SIGNAL("clicked()"), LastcastMainWindow.record)
        QtCore.QObject.connect(self.btnLove, QtCore.SIGNAL("clicked()"), LastcastMainWindow.love)
        QtCore.QObject.connect(self.btnBan, QtCore.SIGNAL("clicked()"), LastcastMainWindow.ban)
        QtCore.QObject.connect(self.btnStations, QtCore.SIGNAL("clicked()"), LastcastMainWindow.showStations)
        QtCore.QObject.connect(self.btnSettings, QtCore.SIGNAL("clicked()"), LastcastMainWindow.showSettings)
        QtCore.QMetaObject.connectSlotsByName(LastcastMainWindow)

    def retranslateUi(self, LastcastMainWindow):
        LastcastMainWindow.setWindowTitle(QtGui.QApplication.translate("LastcastMainWindow", "LastCast v0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.slideVolume.setToolTip(QtGui.QApplication.translate("LastcastMainWindow", "volume", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPlay.setText(QtGui.QApplication.translate("LastcastMainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStop.setText(QtGui.QApplication.translate("LastcastMainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStations.setText(QtGui.QApplication.translate("LastcastMainWindow", "Stations", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBan.setText(QtGui.QApplication.translate("LastcastMainWindow", "Ban", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRecord.setText(QtGui.QApplication.translate("LastcastMainWindow", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLove.setText(QtGui.QApplication.translate("LastcastMainWindow", "Love", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSettings.setText(QtGui.QApplication.translate("LastcastMainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setToolTip(QtGui.QApplication.translate("LastcastMainWindow", "volume", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setToolTip(QtGui.QApplication.translate("LastcastMainWindow", "station", None, QtGui.QApplication.UnicodeUTF8))
        self.editStation.setToolTip(QtGui.QApplication.translate("LastcastMainWindow", "station", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setText(QtGui.QApplication.translate("LastcastMainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setText(QtGui.QApplication.translate("LastcastMainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecord.setText(QtGui.QApplication.translate("LastcastMainWindow", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLove.setText(QtGui.QApplication.translate("LastcastMainWindow", "Love", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBan.setText(QtGui.QApplication.translate("LastcastMainWindow", "Ban", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStations.setText(QtGui.QApplication.translate("LastcastMainWindow", "Stations", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("LastcastMainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))

import lastcast_rc
